export default {
  videobackUrl: "../src/assets/videobackground-baja.mp4",
  name: "Pablo Coronel",
  subtitle: "video maker & editor",
  sections: [
    {category: "about", id: 1 },
    {category: "works", id:2},
    {category:"services",id:3},
    {category:"vita",id:4},
    {category:"contact",id:5},
  ],
  aboutPhoto: "../../src/assets/aboutmephoto-nobg.png",
  logoPhoto: "../../src/assets/logo.png",
  awardsLogo: "../../src/assets/award.svg",
  aboutmeText:
    "My interest in cinematographic processes has led me, during my 20 years in the audiovisual world, to develop my professional skills in editing, photography and directing. I have directed music videos institutional videos, documentaries, tv series, I have shot live concerts, documentaries, tv shows and I have edited all kinds of audiovisual formats (fiction films, tv shows, tv series, music videos, video art, etc...); but my desire to tell stories focused me to make my own documentary films. As a filmmaker, telling documentary stories is what motivates me the most. I love my job and I take every project as a new challenge. I like my work to be as perfect as possible according to the tools and time available for each of them.",
  awards: [
    {
      opus: "Cumbia que te vas de ronda",
      opusSubtitle: "feature documentary",
      prizes: [
        { id:1,
          prizeName: "Jury Special Award and Best in Music Award",
          date: "2021",
          place: "Culture Cinema Film Festival, India",
        },
        {id:2,
          prizeName: "Audience Award",
          date: "2021",
          place: "Latino and Native American Fiilm Festival, USA",
        },
        {id:3,
          prizeName: "Audience Award",
          date: "2021",
          place: "Rencontres du cinéma sud-américain, France",
        },
      ],
    },
    {
      opus: "Cumbia la Reina",
      opusSubtitle: "feature documentary",
      prizes: [
        {
          prizeName: "Honorable mention",
          date: "2015",
          place: "INCAA TV, Argentina",
        },
      ],
    },
    {
      opus: "Nanotecnólogos por un día",
      opusSubtitle: "documentary tv series",
      prizes: [
        {
          prizeName: "New Technologies Award",
          date: "2015",
          place: "Festival de Cine Político, Argentina",
        },
      ],
    },
    {
      opus: "La Lleva",
      opusSubtitle: "documentary tv series",
      prizes: [
        {
          prizeName: "Best Children’s Program",
          date: "2012",
          place: "India Catalina Award, Colombia",
        },
      ],
    },
  ],

  works: [
    {
        id:1,
      title: "Cumbia que te vas de Ronda",
      subtitle: "2020, feature documentary",
      description:
        " CUMBIA QUE TE VAS DE RONDA is a documentary road-movie that follows Pablo Coronel and a group of film-musicians who travel tracing the paths of la Cumbia as a musical phenomenon. With Buenos Aires as its starting point, the documentary covers corners of Latin America, where la Cumbia was born and grew up. Pioneers and references - from Totó la Momposina, to Los Mirlos, Celso Piña, Coco Barcala give their testimony, sharing their knowledge and passion for la Cumbia. Pablo’s dreams is to travel with his team to the East and take la Cumbia there where the culture and the languages spoken are completely different. The group travels to Japan, Vietnam, The Philippines and Cambodia, where la Cumbia is almost unknow, but which will no longer be since Pablo and his team will be willing to share its magic and power with the new public.",
      trailerUrl: "https://www.youtube.com/watch?v=Bh0G2_2xf4U",
      criticText:
        " ´I feel free when I listen to Cumbia´,says Katsumi Tanaka,guitarist of Minyo Crusaders, a Big Band from Tokyo that mixes Cumbia with Japanese folk. Cumbia Que Te Vas De Ronda proposes a journey across different continents in search of some answers. What is Cumbia and why does it generate such joy? In this vivid experimental movie recorded between Argentina, Bolivia, Colombia, Portugal, Philippines, Vietnam and who knows where else, we’ll find notes and testimonies about Memory and Identity, Rites and the Sun, Afro Stanzas and Drum Beats. Cumbia sounds wild, and therein lies its virtue: it doesn’t need expert dancers. Here, there and everywhere, bodies fill with energy when the Cumbia rhythms sneaks in, even across oceans and distant lands, the feeling is always the same. (Hernán Panessi)",
      poster: "./src/assets/poster-cqtvdr.jpeg",
    },
    {
        id:2,
      title: "Cumbia la Reina",
      subtitle: "2015, feature documentary",
      description:
        " CUMBIA LA REINA narrates the phenomenon by which la Cumbia became part of the Argentinean        culture, evolving in its different and new musical fusions, in its costumes, in its ideological content.        From the beginnings in the 50's with Mario Castellón (founder of Los Wawancó), to the 2000's with Pablo Lescano (a referent of the Cumbia Villera), the history of the Argentinean Cumbia is narrated from its protagonists. Interspersed with the different landscapes, geographical and cultural, in which Cumbia has been able to leave its mark.",
      trailerUrl:
        "https://www.cinemargentino.com/films/914988721-cumbia-la-reina",
      criticText:
        "Knees are free. Nobody lives without the experience of cumbia. Anyone who wants to know what it's all about should go dancing. Cumbia is the princess of the street, a hammock for children, the popular music of Latin America. It makes you have fun, it takes the sadness out of you. So, in 1955, Los Wawancó were already making everyone dance. Cumbia la reina, a documentary that honours Argentinean tropical music, tells the story of this beginning and its development. The authorities? El Cuarteto Imperial, Los del Trópico, Koli Arce and El Quinteto Imperial. The influence of Colombian cumbia, the arrival of accordion music, the importance of the interior of the country, the democracy of the loudspeaker, the session musicians, the baby faces of the 90s and the word of the poor neighbourhood. Cumbia la reina is pure emotion. And it is also the centrifugal testimony of sincere hearts, of people with joy, of the hottest, most popular and bewitching souls. That is why it is logical: if there is cumbia there will -always- be celebration. (Hernán Panessi)",
      poster: "./src/assets/cumbia-la-reina-poster.png",
    },
  ],
  otherWorks: [
    { id:1,
      title: "Prosap",
      subtitle: "Ministry of Agriculture, Argentina",
      description: "",
      trailerUrl:"https://www.youtube.com/embed/YfID6E3z-Ok?controls=0",
      criticText: " ",
      poster: "",
    },
    { id:2,
      title: "Estampida",
      subtitle: "León Ferrari Foundation",
      description: "",
      trailerUrl:"https://www.youtube.com/embed/CtX7W5mqZKQ?controls=0",
      criticText: " ",
      poster: "",
    },
    { id:3,
      title: "Denver Farma SA",
      subtitle: "...",
      description: "",
      trailerUrl:"https://www.youtube.com/embed/JxVtdUIjDGM?controls=0&amp;start=115" ,
      criticText: "",
      poster: "",
    },
    {id:4,
      title: "90’s Pop Tour",
      subtitle: "VEVO",
      description: "",
      trailerUrl:"https://www.youtube.com/embed/K4IEJM3XvXE?controls=0",
      criticText: "",
      poster: "",
    },
    {id: 5,
      title: "Exploración Maya",
      subtitle: "History Channel, México",
      description: "",
      trailerUrl: "https://www.youtube.com/embed/RD51nFxfW5k?controls=0&amp;start=2k",
      criticText: "",
      poster: "",
    },
    {id:6,
      title: "Santiagueños",
      subtitle: "Canal Encuentro, Argentina ",
      description: "",
      trailerUrl: "https://www.youtube.com/embed/5m0UUrE4lf8?controls=0&amp",
      criticText: "",
      poster: "",
    },
    {id:7,
      title: "Ter Pressa",
      subtitle: "Diogo Picão",
      description: "",
      trailerUrl: "https://www.youtube.com/embed/aX9kNXr20-E?controls=0&amp",
      criticText: "",
      poster: "",
    },
    {id:8,
      title: "Malagueña",
      subtitle: "Mariachi Sol de Lisboa",
      description: "",
      trailerUrl: "https://www.youtube.com/embed/_TXC8Ho8tH8?controls=0",
      criticText: "",
      poster: "",
    },
    {id:9,
      title: "Filmmaker Reel 2022",
      subtitle: "...",
      description: "",
      trailerUrl: "https://player.vimeo.com/video/758497058?h=8ab41ed5ad",
      criticText: "",
      poster: "",
    },
  ],
};
